version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: sudo npm install dredd@5.3.2 --no-optional --global
      - run: dredd apiary.apib http://localhost:3000
